version: "3.0"
sevices:

  elasticsearch:
    image: elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    unlimits:
      memlocks:
        soft: -1
        hard: -1
    volumes:
      esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200


  web:
    build:
      context: ./services/web
      command: sh run.sh
      volumes:
        - ./services/web/:/usr/src/app/
      ports:
        - 5000:5000
      env_file:
        - ./.env
      dockerfile: Dockerfile

      depends_on:
        - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=flask_app
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=flask_app_dev
volumes:
  postgres_data:
